### ISSUE TITLE
Screens/WebUI Gif support

### ISSUE THREAD

**Issue by VaughnRupp** [opensourceautomation/Open-Source-Automation#285]
A new control supporting Gif should be tested and decide is it is suitable for all animation, or leave it as a separate control.

**Comment by KHerron** [comment]
I have created a simple work around for this, on my setup.
We could implement it for now, and then decide if we want to use a different approach latter.

Basically, I saved a GIF image(Ceiling Fan) to the "wwwroot/Images" folder that has the same name as Image 1 for the state image On or Off states. Then, in the control, IF it finds a file with the same name as Image 1, it uses that gif file instead, otherwise, it still uses the image from the DB. Kinda clumsy, but it does work nicely and I now have animated ceiling fans on both the Screens and the WebUI!!

I looked in to encoding the four separate images in to an animated gif, and It can be done that way, but is slow, and still has to be saved, before you can use it. Also converting to a Byte[] to save in the database destroys the animation header information and the file crashes. So this was the quickest fix I could find at the time!

**Comment by KHerron** [comment]
OK, I just manually inserted a GIF image in to the database using Workbench. When I go to the Images page in the WebUI, the GIF image displays correctly with animation!

So, what if we make the Screens application pull each fame from the GIF, and populate Image1, Image2, Image3 and Image4 automatically from the Gif, instead of setting each image. This way there is only 1 image used, and they would work in both scenario's (Screen and WebUI)

**Comment by KHerron** [comment]
I will try to solve this issue without using my "clumsy" workaround above for 0.5.0.
We should be able to pull and convert each frame from a Gif to a PNG.
Then we could use these in the Screens application for animation, and the GIF for the WebUI Screens, thus  only requiring 1 image to be used.

**Comment by KHerron** [comment]
Would you be willing to use a 3rd party Library?

Check this out: [https://github.com/XamlAnimatedGif/WpfAnimatedGif](url)

**Comment by KHerron** [comment]
I have been working on this for weeks now, trying to use my own code. But to no avail, I was not getting anything accomplished but wasting time. Today I decided to try the WpfAnimatedGif Nuget package I mentioned above, and it works. It works GREAT! I am going to test this with some other gif images to see what I get. We will need to update the code for the Image Manager to allow gif files to be added to the DB. I will also need to test the WebUI screens for proper execution, but that should not be an Issue.

**Comment by KHerron** [comment]
Making GREAT progress with this. I have added animated gif to the Image selection screen, and the Add StateImage control. Even the Re-Sizing is working great in the Screens app.

However, the question we need to answer now, is, do we leave the manual animation in there (4 still images), or to we take that code out? If we leave it in there, we have to make it animate on the WebUI Screens

**Comment by KHerron** [comment]
I have now made changes to the ImageManager, and I can now add animated gif images to the DB via the screens application and the WebUI Images page. Will be committing these changes fairly soon, as long as there are no objections.

**Comment by VaughnRupp** [comment]
Good work.   Please leave the existing code in place until at least after a round of testing with all the Demo graphics converted.   And maybe we leave it in for 1 release to give people time to convert graphics and test, then take out the old stuff in the following release.

This is in the 5.0 Milestone, it sounds like it can make the 049 release if you want, update the ticket and I will start testing and making new gif for the demo set.

**Comment by KHerron** [comment]
Having both options available is not really a problem, other than getting the manual animation to work on the WebUI screens pages. I guess we could always Poll the users on the forums, and see how many would want the old option to stay. But for now, I will leave the old code alone, and will also hold off on trying to animate it in the WebUI.

**Comment by VaughnRupp** [comment]
I would ignore the manual animation, I think gif is good.   Just need to leave the old way for a minute to give people a bit to transition and test.

**Comment by KHerron** [comment]
Vaughn, Feel free to close this once you have tested and feel comfortable with the results.

**Comment by KHerron** [comment]
I do believe this issue has been thoroughly tested, and can be closed.
I changed the milestone to 049, as it will be going out in the next release.
