### ISSUE TITLE
WebUI - Object Type Data Type

### ISSUE THREAD

**Issue by VaughnRupp** [opensourceautomation/Open-Source-Automation#348]
If you select the data type of "Object Type" for a property, it needs to force the selection of the underlying object_type.

**Comment by KHerron** [comment]
I can definitely fix this on the Object Types page, if you want me to assign myself.
But since you brought it up, I do feel we need some "Validation" on the WebUI pages, sort or like what we added to the screens application. I also think it would be nice to add a Boolean named "Required" to properties. Then we could do validation on missing information that is required, and prompt users to enter the missing information.

**Comment by KHerron** [comment]
Been offline due to the hurricane Matthew!

This should close this issue out!
