### ISSUE TITLE
Can't login to OSA forum

### ISSUE THREAD

**Issue by Automate1** [opensourceautomation/Open-Source-Automation#365]
I have not been able to login to the OSA forum this year.  I get a PHP error.  Is anyone else having this issue or is it just my account or browser? I even tried creating a brand new users account but still get the same error.

`[phpBB Debug] PHP Warning: in file [ROOT]/includes/captcha/captcha_factory.php on line 36: include(./includes/captcha/plugins/phpbb_captcha_sortables_plugin.php) [function.include]: failed to open stream: No such file or directory
[phpBB Debug] PHP Warning: in file [ROOT]/includes/captcha/captcha_factory.php on line 36: include(./includes/captcha/plugins/phpbb_captcha_sortables_plugin.php) [function.include]: failed to open stream: No such file or directory
[phpBB Debug] PHP Warning: in file [ROOT]/includes/captcha/captcha_factory.php on line 36: include() [function.include]: Failed opening './includes/captcha/plugins/phpbb_captcha_sortables_plugin.php' for inclusion (include_path='.:/usr/local/php53/pear')
[phpBB Debug] PHP Warning: in file [ROOT]/includes/captcha/captcha_factory.php on line 38: call_user_func() expects parameter 1 to be a valid callback, class 'phpbb_captcha_sortables' not found

Fatal error: Call to a member function init() on a non-object in /home/openso14/public_html/phpBB3/includes/ucp/ucp_register.php on line 165`

**Comment by KHerron** [comment]
Very Strange.

I know the site was down at one time, but it wasn't that long.
I can see it in all standard browsers (IE, Chrome, Firefox, etc..)

Have you tried from a different device? (Phone, tablet, laptop)

**Comment by VaughnRupp** [comment]
We were having PHP errors due to outdated modules in the site.   I paid Siteground to upgrade everything and I think it fixed everything.   If anyone is still having issues, you can email me at vaughnrupp@ either yahoo.com or gmail.com.   People are also welcome to use Hangouts to talk live about things.

Vaughn

**Comment by Automate1** [comment]
I'm still having the same problem.  I have tried Chrome, Internet Explorer and Edge.

The error message has changed slightly from my 1st post.  Here is what I'm getting now

[phpBB Debug] PHP Warning: in file [ROOT]/includes/captcha/captcha_factory.php on line 36: include(./includes/captcha/plugins/phpbb_captcha_sortables_plugin.php) [function.include]: failed to open stream: No such file or directory
[phpBB Debug] PHP Warning: in file [ROOT]/includes/captcha/captcha_factory.php on line 36: include(./includes/captcha/plugins/phpbb_captcha_sortables_plugin.php) [function.include]: failed to open stream: No such file or directory
[phpBB Debug] PHP Warning: in file [ROOT]/includes/captcha/captcha_factory.php on line 36: include() [function.include]: Failed opening './includes/captcha/plugins/phpbb_captcha_sortables_plugin.php' for inclusion (include_path='.:/usr/local/php53/pear')
[phpBB Debug] PHP Warning: in file [ROOT]/includes/captcha/captcha_factory.php on line 38: call_user_func() expects parameter 1 to be a valid callback, class 'phpbb_captcha_sortables' not found

Fatal error: Call to a member function init() on a non-object in /home/openso14/public_html/phpBB3/includes/auth/auth_db.php on line 141

**Comment by KHerron** [comment]
Hmmm..  I don't understand what it could be. 
According to Chrome Developer Tools, the only error on the page is
`GET http://opensourceautomation.com/phpBB3/mobiquo/tapatalkdetect.js net::ERR_ABORTED`
This is only because it can not find the "TapATalk" js file. But it souldn't stop you from seeing the page.

Do you get the Login screen, or does the error happen as soon as you go to the URL?
Have you deleted any old cookies that my still be lingering around?

**Comment by Automate1** [comment]
Yes, the login screen displays.  But after entering the username and password and clicking the login button I get the error.

**Comment by KHerron** [comment]
So, if you can see the login screen, then you should also be able see all the post.
You just can't login??

Maybe there is an issue with your account?? I think Vaughn will have to investigate this one.

**Comment by KHerron** [comment]
Have we had any luck with this.
This maybe why there is so little activity in the forums and the last new user was way back on Wed Aug 31, 2016.

**Comment by VaughnRupp** [comment]
Well, I see it is just captcha security, and the folder it is looking for is missing.   I can't really say much else right now as I am on the low side of a manic swing because nothing is going right for me, and everything I try to work on creates 10 times the problems, etc.    Anyways, I have spend an hour trying to type this even, so I will just stop here and keep trying to get somewhere on anything...   (OSA installer is broke and won't even connect to a DB anymore, I think it is just the DB install, but just sick of setbacks)

**Comment by VaughnRupp** [comment]
Ok, this is fixed.   sorry for the troubles.

**Comment by KHerron** [comment]
@Automate1,

Can you verify or inform us if this fixed your issue?

**Comment by Automate1** [comment]
Yes, it's working now.  Thanks!
